'use client';

import { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import Link from 'next/link';
import { Logo } from '@/components/brand/logo';
import { ChatIcon, CloseIcon, SearchIcon, ThumbsDownIcon, ThumbsUpIcon } from '@/components/ui/emoji-icons';

const categories = ['General', 'Orders', 'Payments', 'Account', 'Recommendations'];

const faqData: Record<string, { q: string; a: string }[]> = {
  General: [
    { q: 'What is CogniCart?', a: 'CogniCart is an AI-powered e-commerce platform that uses hybrid recommendation technology combining collaborative filtering, deep learning, and content-based analysis to personalize your shopping experience.' },
    { q: 'How does the AI recommendation work?', a: 'Our AI analyzes your browsing history, purchase patterns, product preferences, and similar user behavior to surface items tailored specifically to your taste. The system learns and improves with every interaction.' },
    { q: 'Is CogniCart free to use?', a: 'Yes, creating an account and browsing recommendations is completely free. We offer premium tiers with advanced analytics and priority support for power shoppers.' },
    { q: 'Which countries do you support?', a: 'CogniCart is available in 50+ countries globally. We are continuously expanding to new regions. Check the availability list in your account settings.' },
  ],
  Orders: [
    { q: 'How do I track my order?', a: 'Go to Orders in your dashboard. Each order has a tracking number and real-time status updates. You can also enable SMS notifications for delivery updates.' },
    { q: 'Can I cancel or modify an order?', a: 'Orders can be modified or cancelled within 30 minutes of placement. After that, the order enters processing and cannot be changed. Contact support for urgent changes.' },
    { q: 'What is the return policy?', a: 'We offer 30-day returns for most items. Products must be unused and in original packaging. AI-recommended items have a 45-day extended return window.' },
    { q: 'How long does shipping take?', a: 'Standard shipping takes 5-7 business days. Express shipping (2-3 days) and same-day delivery are available in select areas. Free shipping on orders over $50.' },
  ],
  Payments: [
    { q: 'What payment methods do you accept?', a: 'We accept Visa, Mastercard, American Express, PayPal, Apple Pay, Google Pay, and cryptocurrency (BTC, ETH, USDC). All payments are processed securely.' },
    { q: 'Is my payment information secure?', a: 'Absolutely. We use 256-bit SSL encryption, PCI-DSS Level 1 compliance, and tokenization. Your full payment details are never stored on our servers.' },
    { q: 'Do you offer installment payments?', a: 'Yes, we partner with Affirm and Klarna to offer buy-now-pay-later options. Check eligibility at checkout — approval is instant and does not affect your credit score.' },
    { q: 'How do I get a refund?', a: 'Refunds are processed within 5-7 business days after the returned item is received. The amount is credited to your original payment method. AI-recommended items get priority processing.' },
  ],
  Account: [
    { q: 'How do I create an account?', a: 'Click "Get Started" on the homepage. Enter your name, email, and create a password. You can also sign up with Google or Apple for instant access.' },
    { q: 'How do I reset my password?', a: 'Go to the login page and click "Forgot Password". Enter your email and we will send a reset link. Links expire after 30 minutes for security purposes.' },
    { q: 'Can I change my email address?', a: 'Yes, go to Settings > Account > Email. You will need to verify the new email before the change takes effect. Your old email will remain active until verification.' },
    { q: 'How do I delete my account?', a: 'Navigate to Settings > Account > Delete Account. This action is irreversible and permanently removes your data from our systems within 14 days.' },
  ],
  Recommendations: [
    { q: 'Why am I seeing these recommendations?', a: 'Recommendations are generated by our hybrid AI engine based on your browsing history, purchases, wishlist items, and patterns from similar users. You can refine preferences in Settings.' },
    { q: 'How can I improve my recommendations?', a: 'Rate products you like or dislike, add items to your wishlist, and browse categories you are interested in. The more you interact, the smarter your recommendations become.' },
    { q: 'Are recommendations real-time?', a: 'Yes, our AI updates recommendations in real-time as you browse. Each click, view, and interaction refines your profile and adjusts suggestions instantly.' },
    { q: 'Can I opt out of AI recommendations?', a: 'You can disable personalized recommendations in Settings > Privacy > Personalization. You will still see popular and trending products instead of AI-curated picks.' },
  ],
};

export default function FAQPage() {
  const [search, setSearch] = useState('');
  const [activeCategory, setActiveCategory] = useState('General');
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const filtered = useMemo(() => {
    const items = faqData[activeCategory] || [];
    if (!search.trim()) return items;
    const q = search.toLowerCase();
    return items.filter(item => item.q.toLowerCase().includes(q) || item.a.toLowerCase().includes(q));
  }, [activeCategory, search]);

  const allCount = Object.values(faqData).flat().length;

  return (
    <div className="min-h-screen">
      <nav className="nav-blur">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/">
            <Logo size="sm" showTagline={false} variant="text" />
          </Link>
          <div className="flex items-center gap-4">
            <Link href="/login" className="text-sm text-[--muted] hover:text-white transition-colors">Sign In</Link>
            <Link href="/register" className="btn-primary text-xs">Get Started</Link>
          </div>
        </div>
      </nav>

      <main className="pt-24 pb-12 px-6">
        {/* Hero */}
        <section className="max-w-4xl mx-auto mb-12">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center">
            <span className="text-xs px-3 py-1 rounded-full bg-[--primary]/15 text-[--primary] border border-[--primary]/20">FAQ</span>
            <h1 className="text-4xl md:text-5xl font-extrabold mt-6 leading-tight">
              Frequently Asked{' '}
              <span className="bg-gradient-to-r from-[--primary] to-[--secondary] bg-clip-text text-transparent">Questions</span>
            </h1>
            <p className="text-[--muted] mt-4 text-lg">{allCount} answers to common questions about CogniCart</p>
          </motion.div>

          {/* Search */}
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }} className="mt-8 max-w-xl mx-auto">
            <div className="glass rounded-full px-5 py-3 flex items-center">
              <svg className="w-4 h-4 text-[--muted] mr-3 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
              <input
                value={search}
                onChange={e => setSearch(e.target.value)}
                placeholder="Search questions..."
                className="bg-transparent outline-none text-sm text-white placeholder-[--muted] w-full"
              />
              {search && (
                <button onClick={() => setSearch('')} className="text-[--muted] hover:text-white text-xs shrink-0 ml-2"><CloseIcon size={14} /></button>
              )}
            </div>
          </motion.div>
        </section>

        {/* Category Tabs */}
        <section className="max-w-4xl mx-auto mb-8">
          <div className="flex gap-2 overflow-x-auto pb-2 justify-center">
            {categories.map(cat => (
              <motion.button
                key={cat} whileHover={{ y: -1 }} whileTap={{ scale: 0.97 }}
                onClick={() => { setActiveCategory(cat); setOpenIndex(null); }}
                className={`px-4 py-2 rounded-lg text-xs font-medium transition-all whitespace-nowrap ${activeCategory === cat
                  ? 'bg-gradient-to-r from-[--primary] to-[--secondary] text-black shadow-lg shadow-[--primary]/20'
                  : 'glass text-[--muted] hover:text-white'
                }`}
              >
                {cat}
                <span className="ml-1.5 text-[10px] opacity-60">({faqData[cat]?.length || 0})</span>
              </motion.button>
            ))}
          </div>
        </section>

        {/* FAQ List */}
        <section className="max-w-4xl mx-auto mb-16">
          <motion.div key={activeCategory} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-3">
            {filtered.length === 0 ? (
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="glass rounded-xl p-10 text-center">
                <span className="text-3xl"><SearchIcon size={14} /></span>
                <p className="text-sm text-[--muted] mt-3">No results found for "{search}"</p>
                <button onClick={() => setSearch('')} className="text-xs text-[--secondary] hover:underline mt-2">Clear search</button>
              </motion.div>
            ) : (
              filtered.map((faq, i) => (
                <motion.div key={i} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.04 }}>
                  <button
                    onClick={() => setOpenIndex(openIndex === i ? null : i)}
                    className="w-full glass rounded-xl p-4 text-left flex items-center justify-between card-3d hover:bg-white/[0.06] transition-colors"
                  >
                    <span className="text-sm font-medium pr-4">{faq.q}</span>
                    <motion.span animate={{ rotate: openIndex === i ? 180 : 0 }} className="text-[--muted] shrink-0">
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                      </svg>
                    </motion.span>
                  </button>
                  <AnimatePresence>
                    {openIndex === i && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.3, ease: 'easeInOut' }}
                        className="overflow-hidden"
                      >
                        <div className="glass rounded-b-xl px-4 pb-4 -mt-1 border-t-0">
                          <p className="text-sm text-[--muted] pt-3 leading-relaxed">{faq.a}</p>
                          <div className="flex gap-3 mt-3 pt-3 border-t border-white/6">
                            <button className="text-[10px] text-[--secondary] hover:underline">Was this helpful? <ThumbsUpIcon size={14} /></button>
                            <button className="text-[10px] text-[--muted] hover:text-white"><ThumbsDownIcon size={14} /></button>
                          </div>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>
              ))
            )}
          </motion.div>
        </section>

        {/* Still Need Help */}
        <section className="max-w-4xl mx-auto">
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} className="glass rounded-2xl p-10 md:p-12 text-center">
            <span className="text-4xl"><ChatIcon size={14} /></span>
            <h2 className="text-2xl font-bold mt-4">Still Need Help?</h2>
            <p className="text-[--muted] mt-2 max-w-md mx-auto">
              Our AI support bot is available 24/7. Can't find what you're looking for? Reach out to our human team.
            </p>
            <div className="flex gap-4 justify-center mt-8 flex-wrap">
              <Link href="/contact" className="btn-primary text-sm px-6 py-2.5">Contact Support</Link>
              <a href="mailto:support@cognicart.ai" className="btn-ghost text-sm px-6 py-2.5">Email Us</a>
            </div>
            <p className="text-[10px] text-[--muted] mt-4">Average response time: under 2 hours</p>
          </motion.div>
        </section>
      </main>

      <footer className="border-t border-white/6 py-8 px-6">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-[--muted]">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-full bg-gradient-to-br from-[--primary] to-[--secondary] flex items-center justify-center text-[8px] text-black font-bold">C</div>
            CogniCart v2.0 — Intelligence Behind Every Purchase
          </div>
          <div className="flex gap-6">
            <Link href="/about">About</Link>
            <span>Privacy</span>
            <span>Terms</span>
            <Link href="/contact">Contact</Link>
          </div>
          <div>&copy; {new Date().getFullYear()} CogniCart. All rights reserved.</div>
        </div>
      </footer>
    </div>
  );
}
